spring:
  application:
    name: demographics
  datasource:
    hikari:
      data-source-properties:
        stringtype: unspecified
    url: jdbc:postgresql://localhost:5432/demographic
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    enabled: false
    user: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.url}/auth/realms/master/protocol/openid-connect/certs
    mvc:
      log-request-details: false
  jpa:
    properties:
      hibernate:
        search:
          lucene_version: LUCENE_CURRENT
          default:
            indexBase: target/lucenefiles
            directory_provider: filesystem
        jdbc.batch_size: 20
        search-model-mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
        hbm2ddl-auto: update
  batch:
    job:
      enabled: false
hapi:
  fhir_version: R4
  fhir:
    supported_resource_types:
      - Patient
      - Consent
      - Organization
keycloak:
  url: http://localhost:8082
abac:
  url: http://localhost:8099

atna.audit:
  host: localhost
  port: 514
