version: 2.1

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 21 * * *"
          filters:
            branches:
              only:
                - nightly-builds
    jobs:
      - test:
          context: org-global
  build_and_test:
    jobs:
      - test:
          context: org-global
      - tag-version:
          requires:
            - test
          filters:
            branches:
              only:
                - /^(release\/v\d+\.\d+\.\d+|hotfix\/v\d+\.\d+\.\d+)$/
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - /^(release\/v\d+\.\d+\.\d+|hotfix\/v\d+\.\d+\.\d+|master|develop)$/
jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - cache-out-maven-dependencies
      - run:
          name: Run unit tests and CVE scan
          command:  ./mvnw clean verify
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_artifacts:
          path: target/site
      - store_artifacts:
          path: target/dependency-check-report.html
      - store_test_results:
          path: ~/test-results
      - sonarcloud/scan
      - cache-in-maven-dependencies
  tag-version:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - configure-git-for-ci-bot
      - run:
          name: Update Snapshot Develop Version
          description: |
            This automatically bumps the application version when there is a commit to release or develop branch
            If the commit is to the develop branch, there is a patch version bump, if the commit is to the
            release branch, we will bump the minor version
          command: |
            VERSION_NUMBER="$(echo $CIRCLE_BRANCH | awk -F'/' '{print $2;}')"
            echo "Updating the application version from the branch to ${VERSION_NUMBER}"
            ./mvnw versions:set -DnewVersion=$VERSION_NUMBER versions:commit

            git commit -am "updated patch version to v${VERSION_NUMBER} [skip ci]"
            git tag -a $VERSION_NUMBER -m "demographics-service release version ${VERSION_NUMBER}"
            git push --set-upstream origin $CIRCLE_BRANCH
            git push origin --tags

            exit 0
            esac

  build_and_deploy:
    docker:
      - image: cimg/openjdk:11.0.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - configure-git-for-ci-bot
      - cache-out-maven-dependencies
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and tag image and push
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
                TAG=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
                git push -u origin master:nightly-build # Make sure that the nightly build branch is up-to-date with master
            elif [ $CIRCLE_BRANCH = "develop" ]; then
                TAG=$CIRCLE_BRANCH
            else
                TAG="$(echo $CIRCLE_BRANCH | awk -F'/' '{print $2;}')-rc$CIRCLE_BUILD_NUM"
            fi
            echo "Publishing Docker image with following tag: ${TAG}"
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            ./mvnw clean install -DskipTests
            docker build -t $DOCKER_USER/demographics-service:$TAG .
            docker push $DOCKER_USER/demographics-service:$TAG
      - cache-in-maven-dependencies

commands:
  configure-git-for-ci-bot:
    steps:
      - add_ssh_keys:
          fingerprints:
            - 63:2f:86:f9:06:47:17:92:ea:24:89:9d:dd:92:ff:af
      - run:
          name: Configure GIT
          command: |
            git config --global user.email "50235421+ehrbase-tech-user@users.noreply.github.com"
            git config --global user.name "ci-bot"
            git remote -v

  cache-out-maven-dependencies:
    steps:
      - run:
          name: Generate Cache Checksum for Maven Dependencies
          command: find /home/circleci/project -name 'pom.xml' | sort | xargs cat > /tmp/num-portal_maven_cache_seed
      - restore_cache:
          key: v1-num-portal-deps-

  cache-in-maven-dependencies:
    steps:
      - save_cache:
          key: v1-num-portal-deps-{{ checksum "/tmp/num-portal_maven_cache_seed" }}
          paths:
            - ~/.m2


orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
